### ISSUE TITLE
Build number throws error if not a simple 1.2.3 type of value

### ISSUE THREAD

**Issue by matteozambon89** [marko-js/marko-starter#1]
In my `package.json` I have `"version": "1.0.0-alpha.1",`.

If I run `marko-starter server` I get:
```
Error: buildNumber: Invalid value: 0-alpha
```

**Comment by austinkelleher** [comment]
Thanks for reporting this issue. It should be fixed now. I published `marko-starter@1.0.4`. Let me know if you see any other issues.
