### ISSUE TITLE
Cannot be installed behind corporate proxy

### ISSUE THREAD

**Issue by PascalLeMerrer** [marko-js/marko-starter#13]
Hello

This project cannot installed behind our corporate proxy (and probably others).
The problem is in package.json: it references git://github.com/mlrawlings/marko-magic.git, instead of https://github.com/mlrawlings/marko-magic.git

**Comment by austinkelleher** [comment]
Copying response from PR #14:

> I apologize for the late response on this. I just published `marko-starter@1.2.1` with a version of `marko-magic` that is published to npm. This issue should be resolve. As a side note, `marko-starter@2` does not require `marko-magic` at all.
