### ISSUE TITLE
lassoConfig always undefined

### ISSUE THREAD

**Issue by matteozambon89** [marko-js/marko-starter#2]
Cannot understand how to set a custom Lasso config.

I tried to create a `~/index.js` looking like
```
module.exports = {
  'lassoConfig': ... // my lasso config here
}
```
but it doesn't get read from `marko-starter`.

I've also tried to set `lassoConfig` as key of my `package.json` but still the same issue.

**Comment by patrick-steele-idem** [comment]
We will be improving the documentation for this project soon, but you should just need to create a `project.js` in the root of your project with a structure similar to the following: https://github.com/marko-js/markojs-website/blob/master/project.js

@austinkelleher When you get a chance, do you mind adding some docs for this project? I'm not sure why the docs did not get moved over from the original repo: https://github.com/mlrawlings/marko-starter/blob/master/README.md

**Comment by matteozambon89** [comment]
@patrick-steele-idem Thanks, I was about to write that I found a solution which is exactly the one you suggested.
By reading the code in `marko-starter` I noticed that there's a way to override the `project.js`.

Mine turned out to be pretty simple:
```
const projectDir = require('app-root-dir').get();

const project = require('marko-starter').projectConfig({
  'dir': projectDir,
  'lassoConfig': require('./config').lasso
})

module.exports = project
```

I'll read the `marko-js/markojs-website` tomorrow over the day and see how I can improve my `project.js` 👍

**Comment by austinkelleher** [comment]
@matteozambon89 I've added a README with some documentation to this project. Hope this helps. Glad you figured out your issue.
